import type { EventConfig } from "@/lib/types/event";

/** Single source of truth for HackaToB 2026 operational data */
export const event: EventConfig = {
  name: "HackaToB 2026",
  tagline: "Innova. Conecta. Impacta.",
  domain: "https://hackatob.cr",
  aliasDomain: "https://hackatob.tobcr.com",
  tobUrl: "https://tobcr.com",
  timezone: "America/Costa_Rica",
  datesLabel: "17–20 de agosto de 2026",
  startIso: "2026-08-17T09:00:00-06:00",
  endIso: "2026-08-20T18:00:00-06:00",
  location: "Tecnológico de Costa Rica · Campus Central, Cartago",
  locationShort: "TEC · Cartago",
  demoDayVenue: "Centro de las Artes",
  capacity: 80,
  teamsMin: 15,
  teamsMax: 20,
  maxTeamSize: 4,
  trackCount: 4,
  modalityCount: 3,
  tracks: [
    { code: "HT", slug: "healthtrack", name: "HealthTrack" },
    { code: "GT", slug: "greentrack", name: "GreenTrack" },
    { code: "FT", slug: "fintrack", name: "FinTrack" },
    { code: "TNBT", slug: "the-next-big-thing", name: "The Next Big Thing" },
  ],
  modalities: ["Ideación", "Prototipado", "MVP funcional"],
  applyUrl: "/postular",
  applyDeadlineLabel: "Agosto 2026 · cupos limitados",
  email: "tob@itcr.ac.cr",
  phone: "+506 7088 0176",
  phoneHref: "tel:+50670880176",
  /** Pending decision: keep personal innovation contact or institutional-only */
  innovationEmail: "derojas@estudiantec.cr",
  innovationPhone: "+506 7006 9315",
  innovationPhoneHref: "tel:+50670069315",
} as const;

export const siteFromEvent = {
  name: event.name,
  tagline: event.tagline,
  domain: event.domain,
  tobUrl: event.tobUrl,
  email: event.email,
  phone: event.phone,
  phoneHref: event.phoneHref,
  innovationEmail: event.innovationEmail,
  innovationPhone: event.innovationPhone,
  innovationPhoneHref: event.innovationPhoneHref,
  location: event.location,
  demoDayVenue: event.demoDayVenue,
  dates: event.datesLabel,
  startIso: event.startIso,
  applyDeadline: event.applyDeadlineLabel,
  applyUrl: event.applyUrl,
  applyMailto: `mailto:${event.innovationEmail}?subject=Inter%C3%A9s%20HackaToB%202026&body=Hola%2C%20quiero%20dejar%20mi%20inter%C3%A9s%20en%20HackaToB%202026.%0A%0ANombre%3A%0AEmail%3A%0ATrack%20de%20inter%C3%A9s%3A%0APerfil%3A%0A`,
  challengeMailto: `mailto:${event.email}?subject=Proponer%20reto%20HackaToB%202026`,
} as const;
